apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 315237559079.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 315237559079.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 16ad7bb8
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
